ALTER TABLE jobs ADD COLUMN IF NOT EXISTS file_type VARCHAR(10) NOT NULL DEFAULT 'image';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS redacted_pdf_path TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS page_count INTEGER;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS pages_done INTEGER NOT NULL DEFAULT 0;
